// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package Protocol;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RootOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional sint64 id = 1;
    boolean hasId();
    long getId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional .Protocol.Some some = 3;
    boolean hasSome();
    Protocol.Protocol.Some getSome();
    Protocol.Protocol.SomeOrBuilder getSomeOrBuilder();
  }
  public static final class Root extends
      com.google.protobuf.GeneratedMessage
      implements RootOrBuilder {
    // Use Root.newBuilder() to construct.
    private Root(Builder builder) {
      super(builder);
    }
    private Root(boolean noInit) {}
    
    private static final Root defaultInstance;
    public static Root getDefaultInstance() {
      return defaultInstance;
    }
    
    public Root getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protocol.Protocol.internal_static_Protocol_Root_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protocol.Protocol.internal_static_Protocol_Root_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional sint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .Protocol.Some some = 3;
    public static final int SOME_FIELD_NUMBER = 3;
    private Protocol.Protocol.Some some_;
    public boolean hasSome() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public Protocol.Protocol.Some getSome() {
      return some_;
    }
    public Protocol.Protocol.SomeOrBuilder getSomeOrBuilder() {
      return some_;
    }
    
    private void initFields() {
      id_ = 0L;
      name_ = "";
      some_ = Protocol.Protocol.Some.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, some_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, some_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Protocol.Protocol.Root parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Protocol.Protocol.Root parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Protocol.Protocol.Root parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Protocol.Protocol.Root parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Protocol.Protocol.Root parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Protocol.Protocol.Root parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Protocol.Protocol.Root parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Protocol.Protocol.Root parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Protocol.Protocol.Root parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Protocol.Protocol.Root parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Protocol.Protocol.Root prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Protocol.Protocol.RootOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protocol.Protocol.internal_static_Protocol_Root_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protocol.Protocol.internal_static_Protocol_Root_fieldAccessorTable;
      }
      
      // Construct using Protocol.Protocol.Root.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSomeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (someBuilder_ == null) {
          some_ = Protocol.Protocol.Some.getDefaultInstance();
        } else {
          someBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protocol.Protocol.Root.getDescriptor();
      }
      
      public Protocol.Protocol.Root getDefaultInstanceForType() {
        return Protocol.Protocol.Root.getDefaultInstance();
      }
      
      public Protocol.Protocol.Root build() {
        Protocol.Protocol.Root result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Protocol.Protocol.Root buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Protocol.Protocol.Root result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Protocol.Protocol.Root buildPartial() {
        Protocol.Protocol.Root result = new Protocol.Protocol.Root(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (someBuilder_ == null) {
          result.some_ = some_;
        } else {
          result.some_ = someBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protocol.Protocol.Root) {
          return mergeFrom((Protocol.Protocol.Root)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Protocol.Protocol.Root other) {
        if (other == Protocol.Protocol.Root.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasSome()) {
          mergeSome(other.getSome());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readSInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              Protocol.Protocol.Some.Builder subBuilder = Protocol.Protocol.Some.newBuilder();
              if (hasSome()) {
                subBuilder.mergeFrom(getSome());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSome(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional sint64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional .Protocol.Some some = 3;
      private Protocol.Protocol.Some some_ = Protocol.Protocol.Some.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Protocol.Protocol.Some, Protocol.Protocol.Some.Builder, Protocol.Protocol.SomeOrBuilder> someBuilder_;
      public boolean hasSome() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public Protocol.Protocol.Some getSome() {
        if (someBuilder_ == null) {
          return some_;
        } else {
          return someBuilder_.getMessage();
        }
      }
      public Builder setSome(Protocol.Protocol.Some value) {
        if (someBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          some_ = value;
          onChanged();
        } else {
          someBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setSome(
          Protocol.Protocol.Some.Builder builderForValue) {
        if (someBuilder_ == null) {
          some_ = builderForValue.build();
          onChanged();
        } else {
          someBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeSome(Protocol.Protocol.Some value) {
        if (someBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              some_ != Protocol.Protocol.Some.getDefaultInstance()) {
            some_ =
              Protocol.Protocol.Some.newBuilder(some_).mergeFrom(value).buildPartial();
          } else {
            some_ = value;
          }
          onChanged();
        } else {
          someBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearSome() {
        if (someBuilder_ == null) {
          some_ = Protocol.Protocol.Some.getDefaultInstance();
          onChanged();
        } else {
          someBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public Protocol.Protocol.Some.Builder getSomeBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSomeFieldBuilder().getBuilder();
      }
      public Protocol.Protocol.SomeOrBuilder getSomeOrBuilder() {
        if (someBuilder_ != null) {
          return someBuilder_.getMessageOrBuilder();
        } else {
          return some_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Protocol.Protocol.Some, Protocol.Protocol.Some.Builder, Protocol.Protocol.SomeOrBuilder> 
          getSomeFieldBuilder() {
        if (someBuilder_ == null) {
          someBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Protocol.Protocol.Some, Protocol.Protocol.Some.Builder, Protocol.Protocol.SomeOrBuilder>(
                  some_,
                  getParentForChildren(),
                  isClean());
          some_ = null;
        }
        return someBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Protocol.Root)
    }
    
    static {
      defaultInstance = new Root(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Protocol.Root)
  }
  
  public interface SomeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional sint64 someId = 1;
    boolean hasSomeId();
    long getSomeId();
    
    // optional string someName = 2;
    boolean hasSomeName();
    String getSomeName();
    
    // optional .Protocol.Some some = 3;
    boolean hasSome();
    Protocol.Protocol.Some getSome();
    Protocol.Protocol.SomeOrBuilder getSomeOrBuilder();
  }
  public static final class Some extends
      com.google.protobuf.GeneratedMessage
      implements SomeOrBuilder {
    // Use Some.newBuilder() to construct.
    private Some(Builder builder) {
      super(builder);
    }
    private Some(boolean noInit) {}
    
    private static final Some defaultInstance;
    public static Some getDefaultInstance() {
      return defaultInstance;
    }
    
    public Some getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protocol.Protocol.internal_static_Protocol_Some_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protocol.Protocol.internal_static_Protocol_Some_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional sint64 someId = 1;
    public static final int SOMEID_FIELD_NUMBER = 1;
    private long someId_;
    public boolean hasSomeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getSomeId() {
      return someId_;
    }
    
    // optional string someName = 2;
    public static final int SOMENAME_FIELD_NUMBER = 2;
    private java.lang.Object someName_;
    public boolean hasSomeName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getSomeName() {
      java.lang.Object ref = someName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          someName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSomeNameBytes() {
      java.lang.Object ref = someName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        someName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .Protocol.Some some = 3;
    public static final int SOME_FIELD_NUMBER = 3;
    private Protocol.Protocol.Some some_;
    public boolean hasSome() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public Protocol.Protocol.Some getSome() {
      return some_;
    }
    public Protocol.Protocol.SomeOrBuilder getSomeOrBuilder() {
      return some_;
    }
    
    private void initFields() {
      someId_ = 0L;
      someName_ = "";
      some_ = Protocol.Protocol.Some.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt64(1, someId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSomeNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, some_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(1, someId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSomeNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, some_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Protocol.Protocol.Some parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Protocol.Protocol.Some parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Protocol.Protocol.Some parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Protocol.Protocol.Some parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Protocol.Protocol.Some parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Protocol.Protocol.Some parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Protocol.Protocol.Some parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Protocol.Protocol.Some parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Protocol.Protocol.Some parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Protocol.Protocol.Some parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Protocol.Protocol.Some prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Protocol.Protocol.SomeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protocol.Protocol.internal_static_Protocol_Some_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protocol.Protocol.internal_static_Protocol_Some_fieldAccessorTable;
      }
      
      // Construct using Protocol.Protocol.Some.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSomeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        someId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        someName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (someBuilder_ == null) {
          some_ = Protocol.Protocol.Some.getDefaultInstance();
        } else {
          someBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protocol.Protocol.Some.getDescriptor();
      }
      
      public Protocol.Protocol.Some getDefaultInstanceForType() {
        return Protocol.Protocol.Some.getDefaultInstance();
      }
      
      public Protocol.Protocol.Some build() {
        Protocol.Protocol.Some result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Protocol.Protocol.Some buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Protocol.Protocol.Some result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Protocol.Protocol.Some buildPartial() {
        Protocol.Protocol.Some result = new Protocol.Protocol.Some(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.someId_ = someId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.someName_ = someName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (someBuilder_ == null) {
          result.some_ = some_;
        } else {
          result.some_ = someBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protocol.Protocol.Some) {
          return mergeFrom((Protocol.Protocol.Some)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Protocol.Protocol.Some other) {
        if (other == Protocol.Protocol.Some.getDefaultInstance()) return this;
        if (other.hasSomeId()) {
          setSomeId(other.getSomeId());
        }
        if (other.hasSomeName()) {
          setSomeName(other.getSomeName());
        }
        if (other.hasSome()) {
          mergeSome(other.getSome());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              someId_ = input.readSInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              someName_ = input.readBytes();
              break;
            }
            case 26: {
              Protocol.Protocol.Some.Builder subBuilder = Protocol.Protocol.Some.newBuilder();
              if (hasSome()) {
                subBuilder.mergeFrom(getSome());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSome(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional sint64 someId = 1;
      private long someId_ ;
      public boolean hasSomeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getSomeId() {
        return someId_;
      }
      public Builder setSomeId(long value) {
        bitField0_ |= 0x00000001;
        someId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSomeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        someId_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string someName = 2;
      private java.lang.Object someName_ = "";
      public boolean hasSomeName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getSomeName() {
        java.lang.Object ref = someName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          someName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSomeName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        someName_ = value;
        onChanged();
        return this;
      }
      public Builder clearSomeName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        someName_ = getDefaultInstance().getSomeName();
        onChanged();
        return this;
      }
      void setSomeName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        someName_ = value;
        onChanged();
      }
      
      // optional .Protocol.Some some = 3;
      private Protocol.Protocol.Some some_ = Protocol.Protocol.Some.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Protocol.Protocol.Some, Protocol.Protocol.Some.Builder, Protocol.Protocol.SomeOrBuilder> someBuilder_;
      public boolean hasSome() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public Protocol.Protocol.Some getSome() {
        if (someBuilder_ == null) {
          return some_;
        } else {
          return someBuilder_.getMessage();
        }
      }
      public Builder setSome(Protocol.Protocol.Some value) {
        if (someBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          some_ = value;
          onChanged();
        } else {
          someBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setSome(
          Protocol.Protocol.Some.Builder builderForValue) {
        if (someBuilder_ == null) {
          some_ = builderForValue.build();
          onChanged();
        } else {
          someBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeSome(Protocol.Protocol.Some value) {
        if (someBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              some_ != Protocol.Protocol.Some.getDefaultInstance()) {
            some_ =
              Protocol.Protocol.Some.newBuilder(some_).mergeFrom(value).buildPartial();
          } else {
            some_ = value;
          }
          onChanged();
        } else {
          someBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearSome() {
        if (someBuilder_ == null) {
          some_ = Protocol.Protocol.Some.getDefaultInstance();
          onChanged();
        } else {
          someBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public Protocol.Protocol.Some.Builder getSomeBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSomeFieldBuilder().getBuilder();
      }
      public Protocol.Protocol.SomeOrBuilder getSomeOrBuilder() {
        if (someBuilder_ != null) {
          return someBuilder_.getMessageOrBuilder();
        } else {
          return some_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Protocol.Protocol.Some, Protocol.Protocol.Some.Builder, Protocol.Protocol.SomeOrBuilder> 
          getSomeFieldBuilder() {
        if (someBuilder_ == null) {
          someBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Protocol.Protocol.Some, Protocol.Protocol.Some.Builder, Protocol.Protocol.SomeOrBuilder>(
                  some_,
                  getParentForChildren(),
                  isClean());
          some_ = null;
        }
        return someBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Protocol.Some)
    }
    
    static {
      defaultInstance = new Some(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Protocol.Some)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocol_Root_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Protocol_Root_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocol_Some_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Protocol_Some_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Protocol.proto\022\010Protocol\">\n\004Root\022\n\n\002id" +
      "\030\001 \001(\022\022\014\n\004name\030\002 \001(\t\022\034\n\004some\030\003 \001(\0132\016.Pro" +
      "tocol.Some\"F\n\004Some\022\016\n\006someId\030\001 \001(\022\022\020\n\010so" +
      "meName\030\002 \001(\t\022\034\n\004some\030\003 \001(\0132\016.Protocol.So" +
      "me"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Protocol_Root_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Protocol_Root_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Protocol_Root_descriptor,
              new java.lang.String[] { "Id", "Name", "Some", },
              Protocol.Protocol.Root.class,
              Protocol.Protocol.Root.Builder.class);
          internal_static_Protocol_Some_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Protocol_Some_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Protocol_Some_descriptor,
              new java.lang.String[] { "SomeId", "SomeName", "Some", },
              Protocol.Protocol.Some.class,
              Protocol.Protocol.Some.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
