/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package controlApi;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;

public class mailSet implements TBase<mailSet, mailSet._Fields>, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("mailSet");

  private static final TField SENDER_ADDRESS_FIELD_DESC = new TField("senderAddress", TType.STRING, (short)1);
  private static final TField WHEN_TO_SEND_FIELD_DESC = new TField("whenToSend", TType.STRING, (short)2);
  private static final TField TEMPLATE_FIELD_DESC = new TField("template", TType.STRING, (short)3);
  private static final TField ADDRESS_BOOK_FIELD_DESC = new TField("addressBook", TType.STRING, (short)4);

  public String senderAddress;
  public String whenToSend;
  public String template;
  public ByteBuffer addressBook;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    SENDER_ADDRESS((short)1, "senderAddress"),
    WHEN_TO_SEND((short)2, "whenToSend"),
    TEMPLATE((short)3, "template"),
    ADDRESS_BOOK((short)4, "addressBook");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SENDER_ADDRESS
          return SENDER_ADDRESS;
        case 2: // WHEN_TO_SEND
          return WHEN_TO_SEND;
        case 3: // TEMPLATE
          return TEMPLATE;
        case 4: // ADDRESS_BOOK
          return ADDRESS_BOOK;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, FieldMetaData> metaDataMap;
  static {
    Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SENDER_ADDRESS, new FieldMetaData("senderAddress", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    tmpMap.put(_Fields.WHEN_TO_SEND, new FieldMetaData("whenToSend", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    tmpMap.put(_Fields.TEMPLATE, new FieldMetaData("template", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    tmpMap.put(_Fields.ADDRESS_BOOK, new FieldMetaData("addressBook", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    FieldMetaData.addStructMetaDataMap(mailSet.class, metaDataMap);
  }

  public mailSet() {
  }

  public mailSet(
    String senderAddress,
    String whenToSend,
    String template,
    ByteBuffer addressBook)
  {
    this();
    this.senderAddress = senderAddress;
    this.whenToSend = whenToSend;
    this.template = template;
    this.addressBook = addressBook;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public mailSet(mailSet other) {
    if (other.isSetSenderAddress()) {
      this.senderAddress = other.senderAddress;
    }
    if (other.isSetWhenToSend()) {
      this.whenToSend = other.whenToSend;
    }
    if (other.isSetTemplate()) {
      this.template = other.template;
    }
    if (other.isSetAddressBook()) {
      this.addressBook = TBaseHelper.copyBinary(other.addressBook);
;
    }
  }

  public mailSet deepCopy() {
    return new mailSet(this);
  }

  @Override
  public void clear() {
    this.senderAddress = null;
    this.whenToSend = null;
    this.template = null;
    this.addressBook = null;
  }

  public String getSenderAddress() {
    return this.senderAddress;
  }

  public mailSet setSenderAddress(String senderAddress) {
    this.senderAddress = senderAddress;
    return this;
  }

  public void unsetSenderAddress() {
    this.senderAddress = null;
  }

  /** Returns true if field senderAddress is set (has been asigned a value) and false otherwise */
  public boolean isSetSenderAddress() {
    return this.senderAddress != null;
  }

  public void setSenderAddressIsSet(boolean value) {
    if (!value) {
      this.senderAddress = null;
    }
  }

  public String getWhenToSend() {
    return this.whenToSend;
  }

  public mailSet setWhenToSend(String whenToSend) {
    this.whenToSend = whenToSend;
    return this;
  }

  public void unsetWhenToSend() {
    this.whenToSend = null;
  }

  /** Returns true if field whenToSend is set (has been asigned a value) and false otherwise */
  public boolean isSetWhenToSend() {
    return this.whenToSend != null;
  }

  public void setWhenToSendIsSet(boolean value) {
    if (!value) {
      this.whenToSend = null;
    }
  }

  public String getTemplate() {
    return this.template;
  }

  public mailSet setTemplate(String template) {
    this.template = template;
    return this;
  }

  public void unsetTemplate() {
    this.template = null;
  }

  /** Returns true if field template is set (has been asigned a value) and false otherwise */
  public boolean isSetTemplate() {
    return this.template != null;
  }

  public void setTemplateIsSet(boolean value) {
    if (!value) {
      this.template = null;
    }
  }

  public byte[] getAddressBook() {
    setAddressBook(TBaseHelper.rightSize(addressBook));
    return addressBook.array();
  }

  public ByteBuffer BufferForAddressBook() {
    return addressBook;
  }

  public mailSet setAddressBook(byte[] addressBook) {
    setAddressBook(ByteBuffer.wrap(addressBook));
    return this;
  }

  public mailSet setAddressBook(ByteBuffer addressBook) {
    this.addressBook = addressBook;
    return this;
  }

  public void unsetAddressBook() {
    this.addressBook = null;
  }

  /** Returns true if field addressBook is set (has been asigned a value) and false otherwise */
  public boolean isSetAddressBook() {
    return this.addressBook != null;
  }

  public void setAddressBookIsSet(boolean value) {
    if (!value) {
      this.addressBook = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SENDER_ADDRESS:
      if (value == null) {
        unsetSenderAddress();
      } else {
        setSenderAddress((String)value);
      }
      break;

    case WHEN_TO_SEND:
      if (value == null) {
        unsetWhenToSend();
      } else {
        setWhenToSend((String)value);
      }
      break;

    case TEMPLATE:
      if (value == null) {
        unsetTemplate();
      } else {
        setTemplate((String)value);
      }
      break;

    case ADDRESS_BOOK:
      if (value == null) {
        unsetAddressBook();
      } else {
        setAddressBook((ByteBuffer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SENDER_ADDRESS:
      return getSenderAddress();

    case WHEN_TO_SEND:
      return getWhenToSend();

    case TEMPLATE:
      return getTemplate();

    case ADDRESS_BOOK:
      return getAddressBook();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SENDER_ADDRESS:
      return isSetSenderAddress();
    case WHEN_TO_SEND:
      return isSetWhenToSend();
    case TEMPLATE:
      return isSetTemplate();
    case ADDRESS_BOOK:
      return isSetAddressBook();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof mailSet)
      return this.equals((mailSet)that);
    return false;
  }

  public boolean equals(mailSet that) {
    if (that == null)
      return false;

    boolean this_present_senderAddress = true && this.isSetSenderAddress();
    boolean that_present_senderAddress = true && that.isSetSenderAddress();
    if (this_present_senderAddress || that_present_senderAddress) {
      if (!(this_present_senderAddress && that_present_senderAddress))
        return false;
      if (!this.senderAddress.equals(that.senderAddress))
        return false;
    }

    boolean this_present_whenToSend = true && this.isSetWhenToSend();
    boolean that_present_whenToSend = true && that.isSetWhenToSend();
    if (this_present_whenToSend || that_present_whenToSend) {
      if (!(this_present_whenToSend && that_present_whenToSend))
        return false;
      if (!this.whenToSend.equals(that.whenToSend))
        return false;
    }

    boolean this_present_template = true && this.isSetTemplate();
    boolean that_present_template = true && that.isSetTemplate();
    if (this_present_template || that_present_template) {
      if (!(this_present_template && that_present_template))
        return false;
      if (!this.template.equals(that.template))
        return false;
    }

    boolean this_present_addressBook = true && this.isSetAddressBook();
    boolean that_present_addressBook = true && that.isSetAddressBook();
    if (this_present_addressBook || that_present_addressBook) {
      if (!(this_present_addressBook && that_present_addressBook))
        return false;
      if (!this.addressBook.equals(that.addressBook))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(mailSet other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    mailSet typedOther = (mailSet)other;

    lastComparison = Boolean.valueOf(isSetSenderAddress()).compareTo(typedOther.isSetSenderAddress());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSenderAddress()) {
      lastComparison = TBaseHelper.compareTo(this.senderAddress, typedOther.senderAddress);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetWhenToSend()).compareTo(typedOther.isSetWhenToSend());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWhenToSend()) {
      lastComparison = TBaseHelper.compareTo(this.whenToSend, typedOther.whenToSend);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTemplate()).compareTo(typedOther.isSetTemplate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTemplate()) {
      lastComparison = TBaseHelper.compareTo(this.template, typedOther.template);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAddressBook()).compareTo(typedOther.isSetAddressBook());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAddressBook()) {
      lastComparison = TBaseHelper.compareTo(this.addressBook, typedOther.addressBook);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // SENDER_ADDRESS
          if (field.type == TType.STRING) {
            this.senderAddress = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // WHEN_TO_SEND
          if (field.type == TType.STRING) {
            this.whenToSend = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // TEMPLATE
          if (field.type == TType.STRING) {
            this.template = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // ADDRESS_BOOK
          if (field.type == TType.STRING) {
            this.addressBook = iprot.readBinary();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.senderAddress != null) {
      oprot.writeFieldBegin(SENDER_ADDRESS_FIELD_DESC);
      oprot.writeString(this.senderAddress);
      oprot.writeFieldEnd();
    }
    if (this.whenToSend != null) {
      oprot.writeFieldBegin(WHEN_TO_SEND_FIELD_DESC);
      oprot.writeString(this.whenToSend);
      oprot.writeFieldEnd();
    }
    if (this.template != null) {
      oprot.writeFieldBegin(TEMPLATE_FIELD_DESC);
      oprot.writeString(this.template);
      oprot.writeFieldEnd();
    }
    if (this.addressBook != null) {
      oprot.writeFieldBegin(ADDRESS_BOOK_FIELD_DESC);
      oprot.writeBinary(this.addressBook);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("mailSet(");
    boolean first = true;

    sb.append("senderAddress:");
    if (this.senderAddress == null) {
      sb.append("null");
    } else {
      sb.append(this.senderAddress);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("whenToSend:");
    if (this.whenToSend == null) {
      sb.append("null");
    } else {
      sb.append(this.whenToSend);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("template:");
    if (this.template == null) {
      sb.append("null");
    } else {
      sb.append(this.template);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("addressBook:");
    if (this.addressBook == null) {
      sb.append("null");
    } else {
      TBaseHelper.toString(this.addressBook, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }

}

