/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace contorlApi
{

  [Serializable]
  public partial class mailSet : TBase
  {
    private string _senderAddress;
    private string _whenToSend;
    private string _template;
    private byte[] _addressBook;

    public string SenderAddress
    {
      get
      {
        return _senderAddress;
      }
      set
      {
        __isset.senderAddress = true;
        this._senderAddress = value;
      }
    }

    public string WhenToSend
    {
      get
      {
        return _whenToSend;
      }
      set
      {
        __isset.whenToSend = true;
        this._whenToSend = value;
      }
    }

    public string Template
    {
      get
      {
        return _template;
      }
      set
      {
        __isset.template = true;
        this._template = value;
      }
    }

    public byte[] AddressBook
    {
      get
      {
        return _addressBook;
      }
      set
      {
        __isset.addressBook = true;
        this._addressBook = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool senderAddress;
      public bool whenToSend;
      public bool template;
      public bool addressBook;
    }

    public mailSet() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              SenderAddress = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              WhenToSend = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              Template = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              AddressBook = iprot.ReadBinary();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("mailSet");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (SenderAddress != null && __isset.senderAddress) {
        field.Name = "senderAddress";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(SenderAddress);
        oprot.WriteFieldEnd();
      }
      if (WhenToSend != null && __isset.whenToSend) {
        field.Name = "whenToSend";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(WhenToSend);
        oprot.WriteFieldEnd();
      }
      if (Template != null && __isset.template) {
        field.Name = "template";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Template);
        oprot.WriteFieldEnd();
      }
      if (AddressBook != null && __isset.addressBook) {
        field.Name = "addressBook";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(AddressBook);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("mailSet(");
      sb.Append("SenderAddress: ");
      sb.Append(SenderAddress);
      sb.Append(",WhenToSend: ");
      sb.Append(WhenToSend);
      sb.Append(",Template: ");
      sb.Append(Template);
      sb.Append(",AddressBook: ");
      sb.Append(AddressBook);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
